# This is a basic workflow to help you get started with Actions

name: CMST 385 PRINCIPLES OF WEB DESIGN AND TECHNOLOGY

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
        -main


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      # Runs a single command using the runners shell
      - name: Deploy to Azure Web App
        use: azure/webapps-deploy@v1

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
         with:
          #Change the app-name to match what was provided to you in the publish settings file, this is in a naming convention of 'COURSENAME-STUDENTUID'

        app-name: 'cmst385-jpressley8'
         slot-name: 'production'
        
              #Change the publish profile to match what you named your secret setup in GitHub, Example shown below

        publish-profile: ${{ secrets.AppServiceCMST385 }}
